### ISSUE TITLE
I can't use sh step on docker agent.

### ISSUE THREAD

**Issue by toto1310** [toto1310/Simple-Jenkins-DooD#2]
Jenkins : 2.102
Docker plugin : 1.1.2
Docker : 17.12.0-c3

> [dood] Running shell script
> sh: can't create /var/jenkins_home/workspace/dood@tmp/durable-38665c0a/jenkins-log.txt: nonexistent directory
> sh: can't create /var/jenkins_home/workspace/dood@tmp/durable-38665c0a/jenkins-result.txt: nonexistent directory

**Comment by toto1310** [comment]
I can use sh step on docker agent if Jenkins is not in docker.
  Jenkins : 2.102
  Docker plugin : 0.16.2 | 1.1.2
  Docker : 17.12.0-c3

**Comment by toto1310** [comment]
relatied issue?
https://github.com/jenkinsci/docker/issues/626

**Comment by zakariaboualaid** [comment]
I have the same issue. Docker on OSX.
Docker 17.12.0-ce
Docker plugin : 1.1.2
Jenkins : 2.104

**Comment by toto1310** [comment]
According to jenkinsci/docker#626 's comment,  this is an issue with docker-workflow-plugin .
https://issues.jenkins-ci.org/browse/JENKINS-49063

So cool!
I can't wait for this release.

**Comment by toto1310** [comment]
Docker-workflow-plugin 1.15 is released.
After I update my jenkins, this issue is not occured.
Great!
